import{a as q,S as v,i}from"./assets/vendor-S2qh7U4E.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const E="56829172-6f8a883684b2b2323b38788f4",$="https://pixabay.com/api/";async function g(t,o){const n={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get($,{params:n})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector(".load-more"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function P(){f.classList.remove("is-hidden")}function l(){f.classList.add("is-hidden")}const R=document.querySelector(".form"),C=document.querySelector(".load-more"),L=document.querySelector(".gallery");let d="",c=1,u=0;R.addEventListener("submit",I);C.addEventListener("click",O);async function I(t){t.preventDefault();const o=t.target.elements.search.value.trim();if(!o){i.warning({message:"Please enter a search query",position:"topRight"});return}d=o,c=1,M(),l();try{p();const n=await g(d,c);if(u=n.totalHits,!n.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}y(n.hits),L.children.length<u?P():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}}async function O(){c+=1,l();try{p();const t=await g(d,c);y(t.hits),T(),(L.children.length>=u||!t.hits.length)&&(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}}function T(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
