import{a as S,S as q,i as s}from"./assets/vendor-S2qh7U4E.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="56829172-6f8a883684b2b2323b38788f4",E="https://pixabay.com/api/";async function h(t,o){const n={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await S.get(E,{params:n})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:a,comments:L,downloads:w})=>`
      <li class="gallery-item">
        <a href="${i}">
        <img class="gallery-image" src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${L}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){f.innerHTML=""}function p(){g.classList.remove("is-hidden")}function b(){g.classList.add("is-hidden")}function M(){m.classList.remove("is-hidden")}function l(){m.classList.add("is-hidden")}const P=document.querySelector(".form"),R=document.querySelector(".load-more"),O=document.querySelector(".gallery");let d="",c=1,u=0;P.addEventListener("submit",C);R.addEventListener("click",I);async function C(t){t.preventDefault();const o=t.target.elements.search.value.trim();if(!o){s.warning({message:"Please enter a search query",position:"topRight"});return}d=o,c=1,B(),l();try{p();const n=await h(d,c);if(u=n.totalHits,!n.hits.length){s.error({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}y(n.hits),n.hits.length<u?M():(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}}async function I(){c+=1;try{p();const t=await h(d,c);y(t.hits),T(),(O.children.length>=u||!t.hits.length)&&(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}}function T(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
